<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

---
# Exercise 1
|**Term**|**Brief description**|
|--|--|
|Subsetting|Selecting elements.|
|Indexing|Selecting one element.|
|Slicing|Selecting a range of elements.|
|Masking|Checking which elements meet certain criteria.|


---
# Exercise 2

In [19]:
import numpy as np
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

num_array = np_array_2d[0:(np_array_2d.size), 0] # making array of numbers
num_array = num_array.astype(int) # set entries to integers
mask = ((num_array % 2) == 1) # make the mask
print(np_array_2d[mask])

[['1' 'A']
 ['3' 'C']
 ['5' 'E']
 ['7' 'G']
 ['9' 'I']]


---
# Exercise 3

In [ ]:
import numpy as np
array = np.array([[66, 50, 57, -1, -1],
                [92, -1, 88, -1, -1],
                [75, -1, -1, 76, -1],
                [-1, 51, 87, -1, -1],
                [71, -1, 67, -1, 69]])

mask_under50 = array[:, :] < 50 #mask for elements under 50
array[mask_under50] = -1 #select elements under 50

mask_above50 = array[:, :] > 50 #mask for elements over 50
array[mask_above50] = 1 #select elements over 50

mask_is50 = array[:, :] == 50 #mask for elemets equal to 50
array[mask_is50] = 0 #select 50

print(array)

[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
